build:
    image: kradalby/ci-tox:latest
    pull: true
    environment:
      - DJANGO_SETTINGS_MODULE=settings.production
    commands:
        # - pip install flake8
        # - make flake8
        - tox

notify:
  email:
    from: drone@fap.no
    host: mail.ntnu.fap.no
    port: 25
    recipients:
      - kradalby@kradalby.no
      - tornvall@stud.ntnu.no
    when:
        branch: master

publish:
  docker:
    registry: registry.fap.no
    repo: turbo/turbo
    tag: latest
    when:
        branch: master
  docker:
    registry: registry.fap.no
    repo: turbo/turbo
    tag: $$TAG
    when:
        event: tag

deploy:
  ssh:
    host:
     - docker.terra.fap.no
    user: root
    port: 22
    sleep: 3
    commands:
      - docker pull registry.fap.no/turbo/turbo:latest
      - docker-compose -f /srv/docker/turbo/docker-compose.yml stop
      - docker-compose -f /srv/docker/turbo/docker-compose.yml up -d
    when:
        branch: master
