pipeline:
  enigma:
    image: node:7.9.0
    pull: true
    commands:
      - cd enigma
      - npm prune
      - npm install -g --silent elm
      - make install
      - make fix_module_canvas
      - mkdir -p src/assets
      - npm run build

  miic:
    image: python:3.6.1
    environment:
      - DJANGO_SETTINGS_MODULE=settings.production
    commands:
      - cd miic
      - pip install tox
      - tox

  docker:
    image: plugins/docker
    repo: registry.fap.no/turbo/turbo
    insecure: true
    tags:
        - latest
    when:
        branch: master

  ssh:
    image: appleboy/drone-ssh
    host:
     - primeape.terra.fap.no
    user: root
    port: 22
    script:
      - docker pull registry.fap.no/turbo/turbo:latest
      - docker-compose -f /srv/docker/turbo/docker-compose.yml stop
      - docker-compose -f /srv/docker/turbo/docker-compose.yml up -d
    when:
        status: success
        branch: master

  notify:
    image: drillster/drone-email
    host: mail.ntnu.fap.no
    port: 25
    from: drone@drone.fap.no
    recipients: [ kradalby@kradalby.no, tornvall@stud.ntnu.no ]
    when:
      status: [ success, changed, failure ]
