version: '2'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # - supersonic
      - turbo
      - elm
    links:
      #      - supersonic
      - turbo
      - elm
        #  supersonic:
        #    image: node:latest
        #    volumes:
        #      - ./:/app
        #    command: bash -c "cd /app; npm run dev"
  turbo:
    build:
        context: .
        dockerfile: Dockerfile.dev
    volumes:
      - .:/srv/app
  elm:
    build:
        context: ../elm-enigma
        dockerfile: Dockerfile
    volumes:
      - ../elm-enigma/:/srv/app
    environment:
      - TMPDIR=/tmp/
    working_dir: /srv/app
    # entrypoint: elm-reactor -a 0.0.0.0 -p 8000
    entrypoint: npm run dev-pub


