version: '2'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - turbo
      - elm
    links:
      - turbo
      - elm
  miic:
    build:
        context: ./miic
        dockerfile: Dockerfile
    volumes:
      - ./miic/:/srv/app
  enigma:
    build:
        context: ./enigma
        dockerfile: Dockerfile
    volumes:
      - ./enigma/:/srv/app
    environment:
      - TMPDIR=/tmp/
    working_dir: /srv/app
    # entrypoint: elm-reactor -a 0.0.0.0 -p 8000
    entrypoint: npm run dev-pub


