version: '2'
services:
    turbo:
        build: .
        volumes:
            - ./test.py:/srv/app/settings/production.py
        ports:
            - "8311:8080"
            - "8312:8080"
        environment:
            - DJANGO_SETTINGS_MODULE=settings.production
