# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('groups', models.ManyToManyField(to='userprofile.UserGroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
