# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 22:24


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testunitresult',
            name='answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testunitresult',
            name='answer_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
