# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-06 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_testunitresult_target_color_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testunitresult',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
