# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-12 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_testunitresult_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='testunitresult',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
