# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-17 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_test_user_can_delete_test_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlineSolutionQuestion',
            fields=[
                ('testunit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.TestUnit')),
                ('original_image', models.ImageField(upload_to='')),
            ],
            bases=('quiz.testunit',),
        ),
        migrations.CreateModel(
            name='OutlineSolutionRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('outline_solution_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.OutlineSolutionQuestion')),
            ],
        ),
    ]
