# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-14 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_outlinesolutionquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('machine', models.CharField(max_length=200)),
                ('reconstruction_method', models.CharField(max_length=200)),
            ],
        ),
    ]
