# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_outlinesolutionquestion_outlinesolutionregion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlinesolutionregion',
            name='outline_solution_question',
        ),
        migrations.DeleteModel(
            name='OutlineSolutionRegion',
        ),
    ]
