# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20160618_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlinesolutionquestion',
            name='outline_region',
            field=models.CharField(default='region', max_length=255),
            preserve_default=False,
        ),
    ]
