# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-15 10:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0010_genericimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.ImageField(upload_to='')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.GenericImage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('outline_suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.ImageSuggestion')),
            ],
        ),
        migrations.RemoveField(
            model_name='testunitresult',
            name='answer_image',
        ),
    ]
