# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='autogenerated',
            field=models.BooleanField(default=False),
        ),
    ]
