# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-13 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_usergroup_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.PositiveSmallIntegerField(default=1337),
            preserve_default=False,
        ),
    ]
