# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-13 16:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20160613_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_changed_password',
            field=models.BooleanField(default=False),
        ),
    ]
