# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 22:42


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_test_user_can_delete_test_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlineSolutionQuestion',
            fields=[
                ('testunit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.TestUnit')),
                ('original_image', models.ImageField(upload_to='')),
                ('outline_region', models.CharField(max_length=255)),
            ],
            bases=('quiz.testunit',),
        ),
    ]
