# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-20 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_outlinesolutionquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericImage',
            fields=[
                ('testunit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.TestUnit')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('machine', models.CharField(max_length=200)),
                ('reconstruction_method', models.CharField(max_length=200)),
            ],
            bases=('quiz.testunit',),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('outline_suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.GenericImage')),
            ],
        ),
    ]
