# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 22:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20160612_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='outline_solution_points',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Points for outline solution questions'),
            preserve_default=False,
        ),
    ]
