# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_globalsettings_outline_solution_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='outline_solution_points',
            field=models.PositiveSmallIntegerField(verbose_name='Points for outline solution questions'),
        ),
    ]
